### PR TITLE
Remove polkit upgrade

### PR DESCRIPTION
**Pull request by seb128**
The package is available in standard mantic now

### CODE REVIEW

**Comment by tim-hm** [comment]
Thanks @seb128. One nitpick, could you follow the conventional commit style please, ie 'feat: remove polkit upgrade'

**Review by tim-hm — CHANGES_REQUESTED** [review]
Thanks @seb128. One nitpick, could you follow the conventional commit style please, ie 'feat: remove polkit upgrade'

**Comment by seb128** [comment]
Thanks, I checked the conventional commit documentation before doing the change but feat is described to be used for feature and removing a step didn't feel like a feature. I've amended the commit to follow your suggestion now though

**Comment by tim-hm** [comment]
it is a bit confusing as the recommended prefixes don't always align . I believe this is because they were pulled from Angular for a very specific use case. Ultimately what I do in practice is use them in a manner that makes sense within the context of the repo rather than following the specification too rigidly. 

Also fyi in the convo with didier yday we decided to follow a slightly different format for the MR commit.

**Review by tim-hm — APPROVED** [review]

**Pull request merged**
