### PR TITLE
feat(devscript): refactor dev serie enablement script

### PR DESCRIPTION
**Pull request by tim-hm**
- Colour code info and warn messages
- Ask the user to confirm before proceeding
- Refactor configs into functions for clearer intention

### CODE REVIEW

**Review by seb128 — COMMENTED** [review]
Thanks, it's an improvement!

I'm not convinced we should use '-y' for the apt calls though. We don't have a real control on the state of the archive at the time the user run the script and we don't know how apt might resolve conflicting situation, it might end up removing gdm and letting the user without a graphical system. It's an experimental script but it feels like having a chance to review the action at the cost of having to press 'y' a few time would be safer.

Let me know if you feel strongly about the -y use there though

**Comment by tim-hm** [comment]
I think you're right, I'll drop `-y` and make a few other tweaks.

**Comment by tim-hm** [comment]
@seb128 changes made. Let me know what you think :pray:

**Review by seb128 — APPROVED** [review]
Great, thanks for the improvements!

**Pull request merged**
